# Generated by Django 3.1.4 on 2020-12-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0002_auto_20201203_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='parents_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category_api.categories', unique=True, verbose_name='Parent'),
        ),
    ]
