# Generated by Django 3.1.4 on 2020-12-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0004_auto_20201204_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='parents_id',
            new_name='parent',
        ),
    ]
