# Generated by Django 3.1.4 on 2021-01-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0005_auto_20201204_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category_api.categories', verbose_name='parent'),
        ),
        migrations.CreateModel(
            name='Siblings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siblings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_api.categories')),
            ],
        ),
    ]
